- bower.json
- index.js
I believe this fixes #9. I've installed this package via npm from my fork and this branch, and `ember server` now works again with the bower `urljs` dependency installed.
> Fix urijs depedency

- addon/mixins/imgix-path-behavior.js
Fixes deprecation warning and associated performance issue in Ember 2.4.2. 
#12
> Defer _incrementResizeCounter out of didInsertElement

- addon/mixins/imgix-path-behavior.js
- tests/unit/components/imgix-image-test.js
In the sliver of time between DOM insertion and the deferred resize 
counter increment, the browser may attempt to load invalid image URLs
with `w=0` or `w=NaN`. On image-heavy pages, these invalid requests may
tie up some browsers' request queue, leading to a delay in loading the
correct URLs generated after the resize trigger fires.
This change causes `src` to return null until a `_width` is available.
> Don't generate src until _width can be determined

- addon/mixins/imgix-path-behavior.js
The debounced calls may be called when the object is destroyed and triggers an error because you can't set properties on destroyed objects.
This introduces a simple guard by checking `isDestroyed` and `isDestroying`
> Guard in Debounced calls

- package.json
To avoid this deprecation warning under Ember 2.6+:
DEPRECATION: Overriding init without calling this._super is deprecated. 
Please call `this._super.init && this._super.init.apply(this, arguments);` 
addon: `ember-cli-htmlbars`
> Update ember-cli-htmlbars dependency

- addon/mixins/imgix-path-behavior.js
Addresses a race condition in more recent ember versions where the
resize counter and width calculation could occur prior to the insertion
of a parent view.
> Schedule _incrementResizeCounter in afterRender queue

- addon/mixins/imgix-path-behavior.js
- tests/unit/components/imgix-image-test.js
Passing a null or undefined path into the component was throwing an
exception along the lines of:
TypeError: undefined is not a valid argument for URI
This adds an existence check on `path` before passing it to URI for parsing.
> Avoid throwing TypeError when path is undefined

- .travis.yml
This PR updates the node versions tested by Travis to current versions.
v8 = latest LTS node version
v10 = latest stable node version
> chore(travis-config): update node versions to current

- README.md
- addon/common/constants.js
- addon/components/imgix-image.js
- addon/mixins/imgix-path-behavior.js
- index.js
- package-lock.json
- package.json
- tests/dummy/app/templates/usage.hbs
- tests/dummy/config/environment.js
- tests/integration/components/imgix-image-wrapped-test.js
- tests/unit/components/imgix-image-test.js
This PR adds an `ixlib` parameter to urls generated by this component. The url parameter is in the form `ixlib=ember-7.1.1`. There are two reasons to add this parameter: a) it helps Imgix support see what versions of libraries that customers are using, and b) it help Imgix to see how many people overall are using the ember library, and the specific versions.
This functionality is enabled by default but can be turned off by passing the parameter `disableLibraryParam={true}` or by setting `disableLibraryParam` to true in the global config. e.g.
```js
// config/environment.js
module.exports = function(environment) {
var ENV = {
// snip
APP: {
imgix: {
// ...
disableLibraryParam: true
}
}
// snip
};
};
```
This closes #2 .
Either review the unit tests or set-up a new app and inspect the …
> feat: add ixlib url parameter to help Imgix support and analytics

- README.md
- addon/components/imgix-image.js
- addon/mixins/imgix-path-behavior.js
- tests/integration/components/imgix-image-test.js
- tests/integration/components/imgix-image-wrapped-test.js
- tests/unit/components/imgix-image-test.js
BREAKING CHANGE: default crop behaviour is now imgix default, not `faces`
This PR removes the default setting for `crop`. The old behaviour may be confusing to new developers, so it is better for them to enable it if they would like the behaviour.
This PR fixes #34 
- [N/A] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
Review the changes to the tests.
> feat: change default crop behaviour to undefined from faces

- addon/common/index.js
- addon/common/lib.js
- addon/components/imgix-image.js
- addon/mixins/imgix-path-behavior.js
- tests/integration/components/imgix-image-wrapped-test.js
- tests/unit/components/imgix-image-test.js
Previously, `dpr` values were not rounded to a 2dp, which meant that some very specific dpr values were added to urls. This precision does not show any noticeable improvement in image quality, and is poor for image loading due to the rate of cache misses.
Now, `dpr` values are rounded to the nearest 2dp, which should improve image load performance.
Is it necessary to update the Readme for this behaviour?
This PR fixes #33 
- [N/A] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
- [N/A] Update the readme
Review the changes to the unit tests.
> feat: constrain precision of dpr to 2 decimal places

- .eslintrc.js
- addon/components/imgix-image.js
- addon/mixins/imgix-path-behavior.js
- index.js
- package-lock.json
- package.json
- tests/dummy/app/components/demo-app-header/template.hbs
- tests/dummy/app/index.html
- tests/integration/components/imgix-image-test.js
- tests/integration/components/imgix-image-wrapped-test.js
- tests/unit/components/imgix-image-test.js
I remade #42. I could not figure out that error. This one works. 
Fixes #41 
(there are other issues in ie 11, mostly around img elements having a default width and height, which breaks the tests where the image should fill its container. I will write up sep ticket)
Tests pass in Safari 9 (which was the original reason I wrote this up)
> chore: use jsuri in favor of window.url to support older browsers

- addon/components/imgix-image-wrapped.js
- index.js
- package-lock.json
- package.json
I pulled in version 1.0.1 to TheDyrt and found some fastboot errors. 
This pull request represents everything I had to do to get it running in fastboot again. 
Here is a bare bones ember-cli app that uses fastboot and ember-cli-imgix. https://github.com/Duder-onomy/fastboot-ember-cli-imgix-test-app
If you pull that down and run the command in the readme you can see that ember-cli-imgix fails in its current configuration. 
If you update your package-lock.json to pull this PR's commit hash, you will see everything working again. 
I think I am going to work on #35 tomorrow and see if I can get some fastboot end to end tests running.
> Hotfix fastboot

- README.md
- addon/common/index.js
- addon/common/targetWidths.js
- addon/components/imgix-image.js
- tests/integration/components/imgix-image-test.js
- tests/unit/components/imgix-image-test.js
This PR fundamentally changes the approach taken to responsiveness. Previously, the image (or component) was rendered with an empty image, and the size of the resulting DOM element was measured. An image was loaded with these dimensions, ensuring that the image loaded was only as large as needed. Now, this component achieves the same behaviour by leveraging new native browser features, srcSet and sizes. This allows the browser to load an appropriate size based on the expected image size, which is calculated based on sizes. This has an added benefit that images can load much quicker as the browser can load them as soon as page layout has completed, or sooner (e.g. if sizes is 100vw). This will work well with Fastboot.
The significant amount of breaking changes makes sense due to a lot of …
> feat: implement responsiveness with srcSet and sizes

- addon/components/imgix-image-wrapped.js
This PR updates the `imgix-image-wrapped` deprecation warning to say it will be removed in v3, rather than v2, as we are about to release v2 earlier than we thought we would be.
>  chore: update imgix-image-wrapped deprecations to be deprecated in v3

- addon/components/imgix-image.js
This PR updates the debug helper (shows the resolution of images) to work with the recent srcset update.
Review changes to implementation. 
Or, if the reviewer would like to check this locally.
1. Clone this PR, `npm install`, etc.
2. Run the examples with `npm run start`. Open the examples in a browser (url will be shown in terminal)
3. Observe that debug information is shown for images.
4. Change debug to `false` in `tests/dummy/config/environment.js`
5. Wait for page to refresh and observe that debug information is hidden.
> fix: update debug params to work with srcset

- addon/components/imgix-image.js
- tests/integration/components/imgix-image-test.js
Previously, the aspect ratio implementation did not generate the height when a width + aspect ratio was passed. This broke the backwards compatibility of this feature. 
This PR fixes that, and will generate either the height when width + ar is passed, or width when height + ar is passed. 
**Note for reviewers:** This PR also incorporates a refactor of the srcset generation logic to make it easier to understand, given the new requirements.
Review new tests.
> fix: generate height when width + ar is given, or vice versa

- README.md
- addon/components/imgix-image.js
- tests/integration/components/imgix-image-test.js
I wanted to be able to specify some default params from the applications config. Specifically, I wanted the `auto='format'` param. While implementing, I noticed the other global config options were untested so I added some tests for those while I was in there. 
* Adds tests for current global configuration options [`debug`, `classNames`, `disableLibraryParam`]
* Adds tests and feature for NEW global configuration option called `defaultParams` which is an object of default params that will be applied to all `src`'s.  
* Adds notes to the readme.
- [NA] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
- [✔️]  Run unit tests to ensure all existing …
> feat: add global default params

- README.md
- addon/common/findClosest.js
- addon/common/index.js
- addon/common/lib.js
- addon/components/imgix-bg.js
- app/components/imgix-bg.js
- tests/integration/components/imgix-background-test.js
This PR adds a new component which enables an image to be rendered as a background behind children components.
This PR has existed for a while in react-imgix, and is being ported over to this library.
Review new tests.
> feat: add container to render image as background behind children

- addon/components/imgix-image.js
- package.json
- tests/unit/components/imgix-image-test.js
Fixes issue [#69](https://github.com/imgix/ember-cli-imgix/issues/69) - we're currently adding a "sizeless" URL to the end of the srcset attributes as a "fallback source" which is incorrect. The "fallback source" for an image element should be provided in the src attribute, not at the end of the srcset list. 
N/A
Every item in the srcset list should include a size descriptor, which in our case is always a width value or a resolution multiplier. Tests are still passing.
> fix: remove fallback src from srcset list

- README.md
As a follow up to #126, changes the npm version badge.
> docs: change npm badge; style changes

- .github/pull_request_template.md
- .travis.yml
This PR changes a few missed references to `master` in this project to `main`, one of which is causing issues for our CI tests.
Serves as a follow up to #151 CC: @frederickfogerty
> chore: change (missed) refs tof master to main

- .circleci/config.yml
[Looks like](https://app.circleci.com/pipelines/github/imgix/ember-cli-imgix/8/workflows/a58efe2e-feab-485a-b7d1-6283f7606aa5/jobs/10/resources) we can afford to just use the large resource_class and save some CircleCI credits
> chore: use large resource_class for circleci build

- package.json
- yarn.lock
Allow newer @embroider/macros versions so consumers can use what they want (ideally this would just be a 1.x version with a ^ but since its prerelease we have to use >=)
> chore: increase range of allowed @embroider/macros

- package.json
- yarn.lock
Bump to ember-get-config@1.0.0 so its versioning can be managed better in consumers. Fwiw we previously allowed versions up till 0.5.0 so this only really will be bumping the minimum version required up one (which was to add better Embroider support).
0.x versions are always a pain to deal with downstream so better to use 1.x now that its out.
Link to a demo app and verify ember-cli-imgix still works as intended.
> fix(deps): bump to ember-get-config@1.0.0

- CONTRIBUTING.md
Running `yarn publish` requires the version number to bumped again, when it was already bumped with `yarn release`
> docs: use npm publish

- addon/components/imgix-bg.js
Update htmlSafe import to @ember/template as the current usage is invalid when using Ember@3.27+. This fixes the following warnings when using these Ember versions (note that ember@3.28 is an LTS so its likely to be the version people use for a while yet).
```
WARNING in ./node_modules/ember-cli-imgix/components/imgix-bg.js 111:11-19
export 'htmlSafe' (imported as 'htmlSafe') was not found in '@ember/string' (possible exports: camelize, capitalize, classify, dasherize, decamelize, getString, getStrings, loc, setStrings, underscore, w)
@ ./components/imgix-bg.js 1:0-78 1:0-78
@ ./assets/my-app 864:9-45
```
This has only been tested using unit tests. It probably is worth testing this against a real world ember app prior to merging (or we send it as its unlikely this will break things).
> fix: update htmlSafe import to @ember/template rather than @ember/string

- addon/components/imgix-image.js
- addon/mixins/imgix-path-behavior.js
Resolves deprecation id: [deprecated-run-loop-and-computed-dot-access](https://deprecations.emberjs.com/v3.x/#toc_deprecated-run-loop-and-computed-dot-access)
Just a deprecation change. 😅  this is an intense PR template...
> chore(deprecations): import `reads` from '@ember/object/computed'

- .circleci/config.yml
Adds an additional test step to our CircleCI process to test successful builds.
Problems with builds can only be detected by CircleCI during the `deploy` step; this step only runs on `main` and prerelease branches. As a result, commits that break builds (included automated dependency updates by Renovate) in many cases might not be detected until after merge.
We now test for a successful `build` step on every branch.
> ci(build): add build test step

- .circleci/config.yml
- package.json
Updates dependencies to remove deprecated `node-sass`. Additionally override's CircleCI's use of `--frozen-lockfile`
> chore: remove node-sass, dynamically update CI lockfile

- package.json
Adds additional scripts to ensure properly updated `dist` prior to release.
Library is not guaranteed to execute a `build` step to properly update `dist` directory prior to deployment; as a result, some libraries include the prior release in their `dist` folder.
We include both a `prepublishOnly` step to ensure that the library executes a build prior to deploying a release.
> ci(deploy): adds prepare
